robodoc.frontend/robodoc.frontend/Models/Medikament.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace robodoc.frontend.Models
{
    public enum Einheiten
    {
        Tabletten,
        Kapseln,
        Tropfen,
        Brausetabletten,
        Kautabletten,
        mg_ml,
        Ampullen,
        Zäpfchen
    }

    public enum Verabreichungsprozess
    {
        oral,
        lingual,
        sublingual,
        intravenoes,
        intraarteriell,
        intramuskulaer,
        kutan,
        subkutan,
        intrakutan,
        perkutan,
        nasal,
        konjunktival,
        rektal,
        vaginal
    }

    [Table("MedikamentTB")]
    public class Medikament
    {
        [Key]
        public Guid id { get; set; }
        [Required(ErrorMessage = "Enter Name")]
        public string name { get; set; }
        [Required(ErrorMessage = "Enter Einheit")]
        public Einheiten? einheit { get; set; }
        [Required(ErrorMessage = "Enter Verabreichungsprozess")]
        public Verabreichungsprozess? verabreichungsprozess { get; set; }
        public IEnumerable<MedikamentTherapie> medikamentTherapies { get; set; }

    }
}

robodoc.frontend/robodoc.frontend/Models/MedikamentTherapie.cs
namespace robodoc.frontend.Models
{
    public class MedikamentTherapie
    {
        public Guid id { get; set; }
        public int menge { get; set; }
        public Guid medikamentId { get; set; }
        public Guid therapieId { get; set; }
    }
}

robodoc.frontend/robodoc.frontend/Models/Patient.cs
using System.ComponentModel.DataAnnotations;

namespace robodoc.frontend.Models
{
    public class Patient
    {
        [Key]
        public Guid id { get; set; }
        [Required]
        public string name { get; set; }
        [Required]
        public string vorname { get; set; }
        [Required]
        public int zimmer { get; set; }
        [Required]
        public DateTime eintrittDatum { get; set; }
        public DateTime? austrittDatum { get; set; }
        public string? anamnese { get; set; }
    }
}

robodoc.frontend/robodoc.frontend/Models/Therapie.cs
using System.ComponentModel.DataAnnotations;

namespace robodoc.frontend.Models
{
    public class Therapie
    {
        [Key]
        public Guid id { get; set; }
        [Required]
        public string name { get; set; }
        public IEnumerable<MedikamentTherapie> medikamentTherapies { get; set; }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Data.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using System.Text.Json;

namespace robodoc.frontend.Pages
{
    public class Medikament
    {
        public string id { get; set; }
        public string name { get; set; }
    }

    public class DataModel : PageModel
    {
        private static readonly HttpClient client = new HttpClient();
        private const string apiMediIdRequest = "https://localhost:44391/api/Medikament/2513513c-2e8d-41f7-aff6-e453eed9e787";
        [BindProperty]
        public IEnumerable<Medikament>? medikament { get; set; }
        public Medikament medi { get; set; }

        public async Task<IActionResult> OnGet()
        {
            await fillMedi();
            medi = medikament.First();
            return Page();
        }

        public async Task fillMedi()
        {
            medikament = JsonSerializer.Deserialize<IEnumerable<Medikament>>(await ApiRequest(apiMediIdRequest));
        }

        public Task<string> ApiRequest(string url)
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));
            return client.GetStringAsync(url);
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace robodoc.frontend.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace robodoc.frontend.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string? Username { get; set; }
        [BindProperty]
        public string? Password { get; set; }
        public string? Msg { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            Username = Username ?? string.Empty;
            Password = Password ?? string.Empty;
            if (Username.Equals("abc") && Password.Equals("123"))
            {
                var identity = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.Name, Username)
                }, CookieAuthenticationDefaults.AuthenticationScheme);
                var principal = new ClaimsPrincipal(identity);
                HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                return RedirectToPage("Welcome");
            }
            else
            {
                Msg = "Invalid";
                return Page();
            }
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Medikament.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;
using System.Text.Json;
using robodoc.frontend.Models;

namespace robodoc.frontend.Pages
{
    public class MedikamentModel : PageModel
    {
        private static readonly HttpClient client = new HttpClient();
        private const string apiRequest = "https://localhost:7277/api/Medikament";
        public IEnumerable<Medikament>? medikament { get; set; }

        public MedikamentModel()
        {
            medikament = new List<Medikament>();
        }

        public async Task<IActionResult> OnGet()
        {
            await FillMedikamente();
            return Page();
        }

        private async Task FillMedikamente()
        {
            medikament = JsonSerializer.Deserialize<IEnumerable<Medikament>>(await ApiRequest(apiRequest));
        }

        private Task<string> ApiRequest(string url)
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));
            return client.GetStringAsync(url);
        }

        public void OnPostUpdate()
        {
            
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Patient.cshtml.cs
using System.Net.Http.Headers;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using robodoc.frontend.Models;

namespace robodoc.frontend.Pages
{
    public class PatientModel : PageModel
    {
        private static readonly HttpClient client = new HttpClient();
        private const string apiRequest = "https://localhost:7277/api/Patient";
        public IEnumerable<Patient>? patient { get; set; }
        public async Task<IActionResult> OnGet()
        {
            await FillPatiente();
            return Page();
        }

        private async Task FillPatiente()
        {
            patient = JsonSerializer.Deserialize<IEnumerable<Patient>>(await ApiRequest(apiRequest));
        }

        private Task<string> ApiRequest(string url)
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));
            return client.GetStringAsync(url);
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Robo.cshtml.cs
using System.Net.Http.Headers;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace robodoc.frontend.Pages
{
    public class RoboModel : PageModel
    {
        private static readonly HttpClient client = new HttpClient();
        private const string apiRoboter = "https://localhost:7277/api/Robo";

        public async Task<IActionResult> OnPostStartRobo()
        {
            await ApiRequest(apiRoboter, new StringContent("\"startRobo\"", Encoding.UTF8, "application/json"));
            return Page();
        }

        private Task<HttpResponseMessage> ApiRequest(string url, HttpContent content)
        {
            return client.PostAsync(url, content);
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Therapie.cshtml.cs
using System.Net.Http.Headers;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using robodoc.frontend.Models;

namespace robodoc.frontend.Pages
{
    public class TherapieModel : PageModel
    {
        private static readonly HttpClient client = new HttpClient();
        private const string apiRequest = "https://localhost:7277/api/Therapie";
        public IEnumerable<Therapie>? therapien { get; set; }

        public async Task<IActionResult> OnGet()
        {
            await FillMedikamente();
            return Page();
        }

        private async Task FillMedikamente()
        {
            therapien = JsonSerializer.Deserialize<IEnumerable<Therapie>>(await ApiRequest(apiRequest));
        }

        private Task<string> ApiRequest(string url)
        {
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));
            return client.GetStringAsync(url);
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Welcome.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace robodoc.frontend.Pages
{
    public class WelcomeModel : PageModel
    {
        public string? Username { get; set; }

        public void OnGet()
        {
            Username = HttpContext.Session.GetString("username");
        }

        public IActionResult OnGetLogout()
        {
            HttpContext.Session.Remove("username");
            return RedirectToPage("Index");
        }
    }
}

robodoc.frontend/robodoc.frontend/Pages/Index.cshtml
@page
@model robodoc.frontend.Pages.IndexModel
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Welcome</title>
</head>
<body>
    <h1>Robodoc welcomes you</h1>
</body>
</html>

robodoc.frontend/robodoc.frontend/Pages/Login.cshtml
@page
@model robodoc.frontend.Pages.LoginModel
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    @Model.Msg
    <form method="post" asp-page="Login">
        <table>
            <tr>
                <td>Username</td>
                <td><input type="text" asp-for="@Model.Username" /></td>
            </tr>
            <tr>
                <td>Password</td>
                <td><input type="password" asp-for="@Model.Password" /></td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td><input type="submit" value="Login"/></td>
            </tr>
        </table>
    </form>
</body>
</html>

robodoc.frontend/robodoc.frontend/Pages/Medikament.cshtml
@page
@model robodoc.frontend.Pages.MedikamentModel
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Medikamente</title>
</head>
<body>
    <h1>Medikamente</h1>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Einheit</th>
                    <th>Verabreichungsprozess</th>
                </tr>
            </thead>
            <tbody id="data" spellcheck="false" contenteditable="true">
                @foreach (var item in @Model.medikament)
                {
                    <tr>
                        <td>@Html.DisplayFor(medi => item.id)</td>
                        <td>@Html.DisplayFor(medi => item.name)</td>
                        <td>@Html.DisplayFor(medi => item.einheit)</td>
                        <td>@Html.DisplayFor(medi => item.verabreichungsprozess)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <form method="post" asp-page-handler="Update">
        <input type="submit" value="Update" />
    </form>
</body>
</html>

robodoc.frontend/robodoc.frontend/Pages/Patient.cshtml
@page
@model robodoc.frontend.Pages.PatientModel
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Patienten</title>
</head>
<body>
<h1>Patienten</h1>
<div class="container">
    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Vornamen</th>
            <th>Zimmer</th>
            <th>Eintrittsdatum</th>
            <th>Austrittsdatum</th>
            <th>Anamnese</th>
        </tr>
        </thead>
        <tbody id="data" spellcheck="false">
        @foreach (var item in @Model.patient) {
            <tr>
                <td>@Html.DisplayFor(pat => item.id)</td>
                <td>@Html.DisplayFor(pat => item.name)</td>
                <td>@Html.DisplayFor(pat => item.vorname)</td>
                <td>@Html.DisplayFor(pat => item.zimmer)</td>
                <td>@Html.DisplayFor(pat => item.eintrittDatum)</td>
                <td>@Html.DisplayFor(pat => item.austrittDatum)</td>
                <td>@Html.DisplayFor(pat => item.anamnese)</td>

            </tr>
        }
        </tbody>
    </table>
</div>
</body>
</html>

robodoc.frontend/robodoc.frontend/Pages/Robo.cshtml
@page
@model robodoc.frontend.Pages.RoboModel
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Roboter</title>
</head>
<body>
<h1>Roboter</h1>
<form method="post" asp-page-handler="StartRobo">
<div class="container">
    <td><input type="submit" value="Start Roboter"/></td>
</div>
</form>
</body>
</html>

robodoc.frontend/robodoc.frontend/Pages/Therapie.cshtml
@page
@model robodoc.frontend.Pages.TherapieModel
@{
    Layout = "_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Therapien</title>
</head>
<body>
    <h1>Therapien</h1>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Medikamente</th>
                </tr>
            </thead>
            <tbody id="data" contenteditable="true" spellcheck="false">
                @foreach (var item in @Model.therapien)
                {
                    <tr>
                        <td>@Html.DisplayFor(medi => item.id)</td>
                        <td>@Html.DisplayFor(medi => item.name)</td>
                        <td>
                            @foreach (var mt in item.medikamentTherapies)
                            {
                                @Html.DisplayFor(t => mt.medikamentId)
                                <br />
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

robodoc.frontend/robodoc.frontend/Pages/Welcome.cshtml
@page
@model robodoc.frontend.Pages.WelcomeModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Welcome</title>
</head>
<body>

    <h1>Welcome @User.Identity.Name</h1>
    <a asp-page="Welcome" asp-page-handler="Logout">Logout</a>
</body>
</html>

robodoc.frontend/robodoc.frontend/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<header>
    <link rel="stylesheet" href="~/css/header.css" />
    <div id="top-header">
        <div id="logo">
            <img src="~/lib/Images/Logo.png" />
        </div>
        <nav>
            <div id="menu">
                <ul>
                    <li class="active"><a href="Index">Home</a></li>
                    <li><a href="Therapie">Therapien</a></li>
                    <li><a href="Medikament">Medikamente</a></li>
                    <li><a href="Patient">Patienten</a></li>
                    <li><a href="Robo">Roboter</a></li>
                    <li><a href="Login">Login</a></li>
                </ul>
            </div>
        </nav>
    </div>   
    <div id="header-image-menu">
    </div>
</header>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>